[package]
name = "lele-build"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
lele = { path = "../.." }
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.8"
ureq = "3.1"

