[model]
source = "hf-hub"
repo = "Supertone/supertonic-2"
revision = "main"

[[model.files]]
file = "onnx/text_encoder.onnx"
dest = "text_encoder.onnx"

[[model.files]]
file = "onnx/duration_predictor.onnx"
dest = "duration_predictor.onnx"

[[model.files]]
file = "onnx/vector_estimator.onnx"
dest = "vector_estimator.onnx"

[[model.files]]
file = "onnx/vocoder.onnx"
dest = "vocoder.onnx"

[[model.files]]
file = "onnx/tts.json"
dest = "onnx/tts.json"

[[model.files]]
file = "onnx/unicode_indexer.json"
dest = "onnx/unicode_indexer.json"

[[model.files]]
file = "voice_styles/M1.json"
dest = "voice_styles/M1.json"

[codegen]
class_name = "Supertonic"
custom_methods = []
